server:
  port: ${PORT:8086}
  # ssl:
  #   key-store: ${HOME}/dev/keystore.p12
  #   key-store-password: starbucks
  #   keyStoreType: PKCS12
  #   keyAlias: tomcat
  # port: ${PORT:8443}

zuul:
  routes:
    quote-service:
      path: /qs/**
    demo:
      path: /quote/**
      url: forward:/quotorama
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    # wx:
    #   path: /weather/**
    #   url: forward:http://api.openweathermap.org/data/2.5/find

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        output:
          destination: test
  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411

# security:
#   user:
#     password: starbucks
#   oauth2:
#     client:
#       accessTokenUri: http://localhost:9999/uaa/oauth/token
#       userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#       clientId: demo
#       clientSecret: demosecret
#     resource:
#       userInfoUri: http://localhost:9999/uaa/user

# Misc
quote: "Whatever the question, coffee is nearly always the answer."
